basic:
    name: 'https://speakeasy.com/'
    environments:
        production: 'https://www.speakeasy.com/'
        staging: ''
        development: ''
    breakpoints:
        - 320
        - 640
        - 1024
        - 1200
        - 1920
    pages:
        - api-design
        - api-design/api-compliance
        - blog
        - blog/5-potential-use-cases-for-Arazzo
        - book-demo
        - changelog
        - changelog/changelog-2022-08-17
        - company
        - contact
        - customers
        - customers/airbyte
        - docs
        - docs/api-contract-tests
        - docs/code-samples/automated-code-sample-urls
        - docs/core-concepts
        - docs/customize-testing/bootstrapping-test-generation
        - docs/customize/authentication/configuration
        - docs/customize/basics
        - docs/customize/code/code-regions/overview
        - docs/enterprise-support
        - docs/integrations/_get-public-url-snippet
        - docs/introduction
        - docs/languages/cpp/methodology-cpp
        - docs/languages/maturity
        - docs/languages/swift/methodology-swift
        - docs/languages/typescript/feature-support
        - docs/manage/breaking-changes
        - docs/prep-openapi/best-practices
        - docs/privacy-policy
        - docs/snippet-ai/integrate-via-react
        - docs/speakeasy-reference/cli/ask
        - docs/terms-of-service
        - guides
        - guides/hooks/env-auth-hook
        - guides/sdks/overlays/internal-external-versions
        - guides/sdks/typescript-monorepo-tips
        - mcp
        - mcp/agents-mcp-real-world-example
        - mcp/transports
        - openapi
        - openapi/arazzo
        - openapi/content/file-uploads
        - openapi/frameworks
        - openapi/frameworks/zod
        - openapi/requests/parameters
        - openapi/requests/parameters/cookie-parameters
        - openapi/responses
        - openapi/responses/errors
        - openapi/schemas/arrays
        - openapi/schemas/objects/polymorphism
        - openapi/security
        - openapi/security/custom-auth
        - openapi/security/security-schemes/security-api-key
        - openapi/servers/server-variables
        - pricing
        - product/api-docs
        - product/api-testing
        - product/mcp-server
        - product/react-query
        - product/sdk-generation
        - product/terraform-generation
        - state-of-api-devex/2025
    monitoring:
        days: {  }
        type: ''
        schedule_time: '12:30 AM'
        schedule_time_zone: Europe/London
        compare_with: last-production
        compare_with_fresh: production
advanced:
    mask: ''
    remove: ''
    isolate: ''
    delay: 15
    scroll: true
    headers:
        - { header: '', value: '' }
    cookies: ''
    custom_js: ''
    custom_css: ''
    mock_content:
        - { selector: '', type: title }
    login:
        type: none
        click_element: false
        click_element_selector: ''
        login_url: ''
        username: ''
        password: ''
        username_selector: ''
        password_selector: ''
        submit_selector: ''
        after_login_selector: ''
    performance:
        workers_production: 30
        workers_nonproduction: 10
        workers_production_delay: 0
        workers_nonproduction_delay: 0
    stabilize: true
